[package]
name = "minizip-sys"
version = "0.2.0"
authors = ["Gergő Róth <roth@bytifex.com>"]
license = "MIT"
edition = "2021"
links = "minizip"

[dependencies]
libc = "0.2.62"

[build-dependencies]
cmake = "0.1.42"
bindgen = "0.68.1"
